version: "3"
services:
  directus:
    image: directus/directus:11.3.5
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    env_file:
      - ./.env
    environment:
      SECRET: "${BE_SECRET_KEY:-secret}"
      ADMIN_EMAIL: "${BE_ADMIN_EMAIL:-secret}"
      ADMIN_PASSWORD: "${BE_ADMIN_PASSWORD:-secret}"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
